/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JsDeobRouteImport } from './routes/js-deob'
import { Route as CryptoLabRouteImport } from './routes/crypto-lab'
import { Route as IndexRouteImport } from './routes/index'

const JsDeobRoute = JsDeobRouteImport.update({
  id: '/js-deob',
  path: '/js-deob',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoLabRoute = CryptoLabRouteImport.update({
  id: '/crypto-lab',
  path: '/crypto-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/js-deob': typeof JsDeobRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/js-deob': typeof JsDeobRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/js-deob': typeof JsDeobRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crypto-lab' | '/js-deob'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crypto-lab' | '/js-deob'
  id: '__root__' | '/' | '/crypto-lab' | '/js-deob'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CryptoLabRoute: typeof CryptoLabRoute
  JsDeobRoute: typeof JsDeobRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/js-deob': {
      id: '/js-deob'
      path: '/js-deob'
      fullPath: '/js-deob'
      preLoaderRoute: typeof JsDeobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto-lab': {
      id: '/crypto-lab'
      path: '/crypto-lab'
      fullPath: '/crypto-lab'
      preLoaderRoute: typeof CryptoLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CryptoLabRoute: CryptoLabRoute,
  JsDeobRoute: JsDeobRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
