/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TextPipelineRouteImport } from './routes/text-pipeline'
import { Route as StringToolsRouteImport } from './routes/string-tools'
import { Route as JsDeobRouteImport } from './routes/js-deob'
import { Route as CurlToCodeRouteImport } from './routes/curl-to-code'
import { Route as CryptoLabRouteImport } from './routes/crypto-lab'
import { Route as CodeFormatRouteImport } from './routes/code-format'
import { Route as AstExplorerRouteImport } from './routes/ast-explorer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsWubiTypingRouteImport } from './routes/tools/wubi-typing'
import { Route as ToolsSbtiTestRouteImport } from './routes/tools/sbti-test'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TextPipelineRoute = TextPipelineRouteImport.update({
  id: '/text-pipeline',
  path: '/text-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StringToolsRoute = StringToolsRouteImport.update({
  id: '/string-tools',
  path: '/string-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const JsDeobRoute = JsDeobRouteImport.update({
  id: '/js-deob',
  path: '/js-deob',
  getParentRoute: () => rootRouteImport,
} as any)
const CurlToCodeRoute = CurlToCodeRouteImport.update({
  id: '/curl-to-code',
  path: '/curl-to-code',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoLabRoute = CryptoLabRouteImport.update({
  id: '/crypto-lab',
  path: '/crypto-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeFormatRoute = CodeFormatRouteImport.update({
  id: '/code-format',
  path: '/code-format',
  getParentRoute: () => rootRouteImport,
} as any)
const AstExplorerRoute = AstExplorerRouteImport.update({
  id: '/ast-explorer',
  path: '/ast-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsWubiTypingRoute = ToolsWubiTypingRouteImport.update({
  id: '/wubi-typing',
  path: '/wubi-typing',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSbtiTestRoute = ToolsSbtiTestRouteImport.update({
  id: '/sbti-test',
  path: '/sbti-test',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ast-explorer': typeof AstExplorerRoute
  '/code-format': typeof CodeFormatRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/curl-to-code': typeof CurlToCodeRoute
  '/js-deob': typeof JsDeobRoute
  '/string-tools': typeof StringToolsRoute
  '/text-pipeline': typeof TextPipelineRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/sbti-test': typeof ToolsSbtiTestRoute
  '/tools/wubi-typing': typeof ToolsWubiTypingRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ast-explorer': typeof AstExplorerRoute
  '/code-format': typeof CodeFormatRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/curl-to-code': typeof CurlToCodeRoute
  '/js-deob': typeof JsDeobRoute
  '/string-tools': typeof StringToolsRoute
  '/text-pipeline': typeof TextPipelineRoute
  '/tools/sbti-test': typeof ToolsSbtiTestRoute
  '/tools/wubi-typing': typeof ToolsWubiTypingRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ast-explorer': typeof AstExplorerRoute
  '/code-format': typeof CodeFormatRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/curl-to-code': typeof CurlToCodeRoute
  '/js-deob': typeof JsDeobRoute
  '/string-tools': typeof StringToolsRoute
  '/text-pipeline': typeof TextPipelineRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/sbti-test': typeof ToolsSbtiTestRoute
  '/tools/wubi-typing': typeof ToolsWubiTypingRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ast-explorer'
    | '/code-format'
    | '/crypto-lab'
    | '/curl-to-code'
    | '/js-deob'
    | '/string-tools'
    | '/text-pipeline'
    | '/tools'
    | '/tools/sbti-test'
    | '/tools/wubi-typing'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ast-explorer'
    | '/code-format'
    | '/crypto-lab'
    | '/curl-to-code'
    | '/js-deob'
    | '/string-tools'
    | '/text-pipeline'
    | '/tools/sbti-test'
    | '/tools/wubi-typing'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/ast-explorer'
    | '/code-format'
    | '/crypto-lab'
    | '/curl-to-code'
    | '/js-deob'
    | '/string-tools'
    | '/text-pipeline'
    | '/tools'
    | '/tools/sbti-test'
    | '/tools/wubi-typing'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstExplorerRoute: typeof AstExplorerRoute
  CodeFormatRoute: typeof CodeFormatRoute
  CryptoLabRoute: typeof CryptoLabRoute
  CurlToCodeRoute: typeof CurlToCodeRoute
  JsDeobRoute: typeof JsDeobRoute
  StringToolsRoute: typeof StringToolsRoute
  TextPipelineRoute: typeof TextPipelineRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-pipeline': {
      id: '/text-pipeline'
      path: '/text-pipeline'
      fullPath: '/text-pipeline'
      preLoaderRoute: typeof TextPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/string-tools': {
      id: '/string-tools'
      path: '/string-tools'
      fullPath: '/string-tools'
      preLoaderRoute: typeof StringToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/js-deob': {
      id: '/js-deob'
      path: '/js-deob'
      fullPath: '/js-deob'
      preLoaderRoute: typeof JsDeobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curl-to-code': {
      id: '/curl-to-code'
      path: '/curl-to-code'
      fullPath: '/curl-to-code'
      preLoaderRoute: typeof CurlToCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto-lab': {
      id: '/crypto-lab'
      path: '/crypto-lab'
      fullPath: '/crypto-lab'
      preLoaderRoute: typeof CryptoLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-format': {
      id: '/code-format'
      path: '/code-format'
      fullPath: '/code-format'
      preLoaderRoute: typeof CodeFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ast-explorer': {
      id: '/ast-explorer'
      path: '/ast-explorer'
      fullPath: '/ast-explorer'
      preLoaderRoute: typeof AstExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/wubi-typing': {
      id: '/tools/wubi-typing'
      path: '/wubi-typing'
      fullPath: '/tools/wubi-typing'
      preLoaderRoute: typeof ToolsWubiTypingRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/sbti-test': {
      id: '/tools/sbti-test'
      path: '/sbti-test'
      fullPath: '/tools/sbti-test'
      preLoaderRoute: typeof ToolsSbtiTestRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsSbtiTestRoute: typeof ToolsSbtiTestRoute
  ToolsWubiTypingRoute: typeof ToolsWubiTypingRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSbtiTestRoute: ToolsSbtiTestRoute,
  ToolsWubiTypingRoute: ToolsWubiTypingRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstExplorerRoute: AstExplorerRoute,
  CodeFormatRoute: CodeFormatRoute,
  CryptoLabRoute: CryptoLabRoute,
  CurlToCodeRoute: CurlToCodeRoute,
  JsDeobRoute: JsDeobRoute,
  StringToolsRoute: StringToolsRoute,
  TextPipelineRoute: TextPipelineRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
