/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextPipelineRouteImport } from './routes/text-pipeline'
import { Route as StringToolsRouteImport } from './routes/string-tools'
import { Route as JsDeobRouteImport } from './routes/js-deob'
import { Route as CurlToCodeRouteImport } from './routes/curl-to-code'
import { Route as CryptoLabRouteImport } from './routes/crypto-lab'
import { Route as CodeFormatRouteImport } from './routes/code-format'
import { Route as IndexRouteImport } from './routes/index'

const TextPipelineRoute = TextPipelineRouteImport.update({
  id: '/text-pipeline',
  path: '/text-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StringToolsRoute = StringToolsRouteImport.update({
  id: '/string-tools',
  path: '/string-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const JsDeobRoute = JsDeobRouteImport.update({
  id: '/js-deob',
  path: '/js-deob',
  getParentRoute: () => rootRouteImport,
} as any)
const CurlToCodeRoute = CurlToCodeRouteImport.update({
  id: '/curl-to-code',
  path: '/curl-to-code',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoLabRoute = CryptoLabRouteImport.update({
  id: '/crypto-lab',
  path: '/crypto-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeFormatRoute = CodeFormatRouteImport.update({
  id: '/code-format',
  path: '/code-format',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-format': typeof CodeFormatRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/curl-to-code': typeof CurlToCodeRoute
  '/js-deob': typeof JsDeobRoute
  '/string-tools': typeof StringToolsRoute
  '/text-pipeline': typeof TextPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-format': typeof CodeFormatRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/curl-to-code': typeof CurlToCodeRoute
  '/js-deob': typeof JsDeobRoute
  '/string-tools': typeof StringToolsRoute
  '/text-pipeline': typeof TextPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code-format': typeof CodeFormatRoute
  '/crypto-lab': typeof CryptoLabRoute
  '/curl-to-code': typeof CurlToCodeRoute
  '/js-deob': typeof JsDeobRoute
  '/string-tools': typeof StringToolsRoute
  '/text-pipeline': typeof TextPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code-format'
    | '/crypto-lab'
    | '/curl-to-code'
    | '/js-deob'
    | '/string-tools'
    | '/text-pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code-format'
    | '/crypto-lab'
    | '/curl-to-code'
    | '/js-deob'
    | '/string-tools'
    | '/text-pipeline'
  id:
    | '__root__'
    | '/'
    | '/code-format'
    | '/crypto-lab'
    | '/curl-to-code'
    | '/js-deob'
    | '/string-tools'
    | '/text-pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeFormatRoute: typeof CodeFormatRoute
  CryptoLabRoute: typeof CryptoLabRoute
  CurlToCodeRoute: typeof CurlToCodeRoute
  JsDeobRoute: typeof JsDeobRoute
  StringToolsRoute: typeof StringToolsRoute
  TextPipelineRoute: typeof TextPipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text-pipeline': {
      id: '/text-pipeline'
      path: '/text-pipeline'
      fullPath: '/text-pipeline'
      preLoaderRoute: typeof TextPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/string-tools': {
      id: '/string-tools'
      path: '/string-tools'
      fullPath: '/string-tools'
      preLoaderRoute: typeof StringToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/js-deob': {
      id: '/js-deob'
      path: '/js-deob'
      fullPath: '/js-deob'
      preLoaderRoute: typeof JsDeobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curl-to-code': {
      id: '/curl-to-code'
      path: '/curl-to-code'
      fullPath: '/curl-to-code'
      preLoaderRoute: typeof CurlToCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto-lab': {
      id: '/crypto-lab'
      path: '/crypto-lab'
      fullPath: '/crypto-lab'
      preLoaderRoute: typeof CryptoLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-format': {
      id: '/code-format'
      path: '/code-format'
      fullPath: '/code-format'
      preLoaderRoute: typeof CodeFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeFormatRoute: CodeFormatRoute,
  CryptoLabRoute: CryptoLabRoute,
  CurlToCodeRoute: CurlToCodeRoute,
  JsDeobRoute: JsDeobRoute,
  StringToolsRoute: StringToolsRoute,
  TextPipelineRoute: TextPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
